-- Seed data compiled from public reporting as of July 2026. Every row cites where the
-- status claim comes from and when it was last checked — treat this as a starting point,
-- not a real-time feed. Update entries via the API (or PUT/POST) as better info comes in.

-- === Long-established core PMC areas: generally reliable piped supply ===
-- (No single dated 2026 article confirms these directly; flagged as general-knowledge
--  baseline in the notes rather than over-claiming a precise source.)
INSERT INTO locality (name, ward, status, latitude, longitude, notes, source_name, source_url, last_verified, verified) VALUES
('Kothrud', 'Kothrud', 'MUNICIPAL', 18.5074, 73.8077, 'Long-established core PMC area with mature piped infrastructure. Not tied to a specific dated 2026 source -- treat as a general baseline and confirm locally if precision matters.', 'General public knowledge (unverified against a specific 2026 report)', NULL, '2026-07-01', true),
('Aundh', 'Aundh-Baner', 'MUNICIPAL', 18.5590, 73.8070, 'Long-established core PMC area with mature piped infrastructure. General baseline, not from a specific dated 2026 source.', 'General public knowledge (unverified against a specific 2026 report)', NULL, '2026-07-01', true),
('Deccan Gymkhana', 'Deccan', 'MUNICIPAL', 18.5162, 73.8412, 'Long-established core PMC area with mature piped infrastructure. General baseline, not from a specific dated 2026 source.', 'General public knowledge (unverified against a specific 2026 report)', NULL, '2026-07-01', true),
('Shivajinagar', 'Shivajinagar', 'MUNICIPAL', 18.5304, 73.8567, 'Long-established core PMC area with mature piped infrastructure. General baseline, not from a specific dated 2026 source.', 'General public knowledge (unverified against a specific 2026 report)', NULL, '2026-07-01', true);

-- === 24x7 Water Supply Project: areas at/near completion (PMC 2026-27 budget) ===
INSERT INTO locality (name, ward, status, latitude, longitude, notes, source_name, source_url, last_verified, verified) VALUES
('Ganeshnagar', NULL, 'MUNICIPAL', 18.4985, 73.8790, 'Water-meter installation under the 24x7 supply project has crossed 90% completion here, indicating piped infrastructure is largely in place.', 'Free Press Journal - Pune Budget 2026-27', 'https://www.freepressjournal.in/pune/pune-budget-2026-27-pmc-to-focus-on-reducing-water-leakage-expanding-supply-to-merged-villages', '2026-03-09', true),
('Sukhsagarnagar', 'Bibwewadi', 'MUNICIPAL', 18.4560, 73.8610, 'Water-meter installation under the 24x7 supply project has crossed 90% completion here, indicating piped infrastructure is largely in place.', 'Free Press Journal - Pune Budget 2026-27', 'https://www.freepressjournal.in/pune/pune-budget-2026-27-pmc-to-focus-on-reducing-water-leakage-expanding-supply-to-merged-villages', '2026-03-09', true);

-- === Areas with confirmed piped supply but recently revised timings (Bhama Askhed scheme) ===
INSERT INTO locality (name, ward, status, latitude, longitude, notes, source_name, source_url, last_verified, verified) VALUES
('Viman Nagar', 'Viman Nagar', 'MIXED', 18.5679, 73.9143, 'Has a piped connection under the Bhama Askhed scheme (timings recently shifted to night/midnight/morning shifts), but also named in resident complaints about tanker dependency -- coverage is uneven across the locality.', 'Punekar News / Free Press Journal', 'https://www.punekarnews.in/pune-water-supply-schedule-revised-in-viman-nagar-lohgaon-dhanori-areas-under-bhama-askhed-scheme/', '2025-12-21', true),
('Lohegaon', 'Lohegaon', 'MIXED', 18.5820, 73.9280, 'Piped Bhama Askhed supply exists with recently revised shift timings, but the locality is also named among merged-village areas with tanker dependency and infrastructure neglect complaints.', 'Punekar News / Free Press Journal', 'https://www.punekarnews.in/pune-water-supply-schedule-revised-in-viman-nagar-lohgaon-dhanori-areas-under-bhama-askhed-scheme/', '2025-12-21', true),
('Dhanori', 'Dhanori', 'MIXED', 18.5730, 73.8990, 'Piped Bhama Askhed supply with recently revised shift timings (previously 6-11am, now split night/midnight/morning).', 'Punekar News', 'https://www.punekarnews.in/pune-water-supply-schedule-revised-in-viman-nagar-lohgaon-dhanori-areas-under-bhama-askhed-scheme/', '2025-07-31', true);

-- === Tanker-dependent localities (merged villages / fringe growth areas) ===
INSERT INTO locality (name, ward, status, latitude, longitude, notes, source_name, source_url, last_verified, verified) VALUES
('Wagholi', NULL, 'TANKER_DEPENDENT', 18.5793, 73.9812, 'Residents report continued tanker dependency despite paying municipal taxes; cited among East Pune areas lacking basic civic amenities.', 'Free Press Journal - PMC Elections 2026', 'https://www.freepressjournal.in/pune/pmc-elections-2026-first-time-voters-from-merged-villages-question-years-of-neglect', '2025-12-21', true),
('Kharadi', NULL, 'TANKER_DEPENDENT', 18.5515, 73.9430, 'Named among East Pune localities with tanker dependency despite contributing heavily to city revenue.', 'Free Press Journal - PMC Elections 2026', 'https://www.freepressjournal.in/pune/pmc-elections-2026-first-time-voters-from-merged-villages-question-years-of-neglect', '2025-12-21', true),
('Chandan Nagar', NULL, 'TANKER_DEPENDENT', 18.5563, 73.9310, 'Named among East Pune localities struggling with tanker dependency alongside broken roads and poor drainage.', 'Free Press Journal - PMC Elections 2026', 'https://www.freepressjournal.in/pune/pmc-elections-2026-first-time-voters-from-merged-villages-question-years-of-neglect', '2025-12-21', true),
('Keshav Nagar (Mundhwa)', 'Ward 41', 'TANKER_DEPENDENT', 18.5390, 73.9330, 'Residents describe daily traffic plus tanker dependency, with new building permissions granted ahead of basic infrastructure.', 'Free Press Journal - PMC Elections 2026', 'https://www.freepressjournal.in/pune/pmc-elections-2026-first-time-voters-from-merged-villages-question-years-of-neglect', '2025-12-21', true),
('Undri', NULL, 'TANKER_DEPENDENT', 18.4370, 73.9250, 'Merged village with residents describing feeling "included on paper but excluded in reality"; no formal municipal water connection in many pockets, per property-buyer guidance.', 'Free Press Journal / Pune Realty Hub', 'https://punerealtyhub.com/blog/pune-property-water-connection-guide', '2026-01-01', true),
('Fursungi', NULL, 'TANKER_DEPENDENT', 18.4650, 73.9550, 'Merged-village locality named among areas with longstanding civic neglect, including water supply.', 'Free Press Journal - PMC Elections 2026', 'https://www.freepressjournal.in/pune/pmc-elections-2026-first-time-voters-from-merged-villages-question-years-of-neglect', '2025-12-21', true),
('Pisoli', NULL, 'TANKER_DEPENDENT', 18.4300, 73.8950, 'Recently merged into PMC but infrastructure still transitioning; developers typically arrange their own borewell/tanker supply rather than a municipal connection.', 'Pune Realty Hub - Water Connection Guide 2026', 'https://punerealtyhub.com/blog/pune-property-water-connection-guide', '2026-01-01', true),
('Ambegaon Budruk', NULL, 'TANKER_DEPENDENT', 18.4460, 73.8500, 'Recently merged into PMC but infrastructure still transitioning; often no municipal water connection, per property-buyer guidance.', 'Pune Realty Hub - Water Connection Guide 2026', 'https://punerealtyhub.com/blog/pune-property-water-connection-guide', '2026-01-01', true),
('Bavdhan Budruk', NULL, 'TANKER_DEPENDENT', 18.5090, 73.7730, 'Named among merged-village areas where residents feel excluded from PMC development benefits.', 'Free Press Journal - PMC Elections 2026', 'https://www.freepressjournal.in/pune/pmc-elections-2026-first-time-voters-from-merged-villages-question-years-of-neglect', '2025-12-21', true),
('Sus', NULL, 'TANKER_DEPENDENT', 18.5610, 73.7540, 'Named among merged-village areas where residents feel excluded from PMC development benefits.', 'Free Press Journal - PMC Elections 2026', 'https://www.freepressjournal.in/pune/pmc-elections-2026-first-time-voters-from-merged-villages-question-years-of-neglect', '2025-12-21', true),
('Hinjewadi Phase 3', NULL, 'TANKER_DEPENDENT', 18.5910, 73.6900, 'Tanker dependency described as "currently very real" for new residential clusters here; largely outside mature PMC piped network.', 'Pune Realty Hub - Water Connection Guide 2026', 'https://punerealtyhub.com/blog/pune-property-water-connection-guide', '2026-01-01', true),
('Maan', NULL, 'TANKER_DEPENDENT', 18.5950, 73.7250, 'Newer micro-market at the PCMC/PMRDA periphery with weaker piped-supply infrastructure.', 'Pune Realty Hub - Water Connection Guide 2026', 'https://punerealtyhub.com/blog/pune-property-water-connection-guide', '2026-01-01', true),
('Marunji', NULL, 'TANKER_DEPENDENT', 18.5980, 73.7100, 'Newer micro-market at the PCMC/PMRDA periphery with weaker piped-supply infrastructure.', 'Pune Realty Hub - Water Connection Guide 2026', 'https://punerealtyhub.com/blog/pune-property-water-connection-guide', '2026-01-01', true);

-- === Pipeline / infrastructure work actively underway ===
INSERT INTO locality (name, ward, status, latitude, longitude, notes, source_name, source_url, last_verified, verified) VALUES
('Baner', 'Aundh-Baner', 'PIPELINE_IN_PROGRESS', 18.5590, 73.7860, 'Longstanding water-shortage complaints (subject of an earlier Bombay High Court PIL); now within the PMC 24x7 water supply project''s pipeline and storage-tank expansion, per the 2026-27 budget.', 'PMC Budget 2026-27 (Free Press Journal)', 'https://www.freepressjournal.in/pune/pune-budget-2026-27-pmc-to-focus-on-reducing-water-leakage-expanding-supply-to-merged-villages', '2026-03-09', true),
('Balewadi', NULL, 'PIPELINE_IN_PROGRESS', 18.5680, 73.7730, 'Longstanding water-shortage complaints (subject of an earlier Bombay High Court PIL); now within the PMC 24x7 water supply project''s pipeline and storage-tank expansion, per the 2026-27 budget.', 'PMC Budget 2026-27 (Free Press Journal)', 'https://www.freepressjournal.in/pune/pune-budget-2026-27-pmc-to-focus-on-reducing-water-leakage-expanding-supply-to-merged-villages', '2026-03-09', true),
('Jambhulwadi', NULL, 'PIPELINE_IN_PROGRESS', 18.4460, 73.8250, 'Part of the merged-village cluster (with Wadachiwadi, Mangdewadi) budgeted for expanded PMC water supply as newly merged areas are brought onto the network.', 'PMC Budget 2026-27 (Free Press Journal)', 'https://www.freepressjournal.in/pune/pune-budget-2026-27-pmc-to-focus-on-reducing-water-leakage-expanding-supply-to-merged-villages', '2026-03-09', true);
